server.port=9091
spring.application.name=circuit-breaker-gateway

# Route Config with Circuit Breaker filter pointing to local fallback endpoint
spring.cloud.gateway.routes[0].id=account_route
spring.cloud.gateway.routes[0].uri=http://localhost:8099
spring.cloud.gateway.routes[0].predicates[0]=Path=/accounts/**
spring.cloud.gateway.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.name=accountCircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.fallbackUri=forward:/fallback/account

# Resilience4j Circuit Breaker configuration
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.accountCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.accountCircuitBreaker.slidingWindowSize=5
resilience4j.circuitbreaker.instances.accountCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.accountCircuitBreaker.waitDurationInOpenState=5s
