server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: http://localhost:8085
        predicates:
        - Path=/customers/**
      - id: billing-service
        uri: http://localhost:8086
        predicates:
        - Path=/billing/**
