
CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    ActionDate DATE,
    ActionDetails VARCHAR2(255)
);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (TransactionID, ActionDate, ActionDetails)
    VALUES (
        :NEW.TransactionID, 
        SYSDATE, 
        'Inserted ' || :NEW.TransactionType || ' of $' || :NEW.Amount || ' for AccountID: ' || :NEW.AccountID
    );
END;
/
