server.port=8084
spring.application.name=sso-client

# OAuth2 Client settings
spring.security.oauth2.client.registration.my-client.client-id=mock-client-id
spring.security.oauth2.client.registration.my-client.client-secret=mock-client-secret
spring.security.oauth2.client.registration.my-client.scope=openid,profile,email
spring.security.oauth2.client.registration.my-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.my-client.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.my-client.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.my-client.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.my-client.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.my-client.user-name-attribute=sub
